# Generated by Django 5.2.5 on 2025-08-26 20:27

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=analyzer.models.audio_file_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("stress_score", models.FloatField(blank=True, null=True)),
                ("feature_breakdown", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
